const TYPES = {
  RepositoryAdmin: 'RepositoryAdmin',
  RepositoryApresentacaoEspecialidade: 'RepositoryApresentacaoEspecialidade',
  RepositoryAvaliacao: 'RepositoryAvaliacao',
  RepositoryConfirmacaoPresenca: 'RepositoryConfirmacaoPresenca',
  RepositoryEndereco: 'RepositoryEndereco',
  RepositoryEspecialidade: 'RepositoryEspecialidade',
  RepositoryEspecialidadeServico: 'RepositoryEspecialidadeServico',
  RepositoryEvento: 'RepositoryEvento',
  RepositoryGeneroMusical: 'RepositoryGeneroMusical',
  RepositoryGeneroServico: 'RepositoryGeneroServico',
  RepositoryApresentacaoGenero: 'RepositoryApresentacaoGenero',
  RepositoryMidia: 'RepositoryMidia',
  RepositoryPerfil: 'RepositoryPerfil',
  RepositoryServico: 'RepositoryServico',
  RepositorySolicitacao: 'RepositorySolicitacao',
  RepositoryUsuario: 'RepositoryUsuario',

  ServiceAdmin: 'ServiceAdmin',
  ServiceAvaliacao: 'ServiceAvaliacao',
  ServiceConfirmacaoPresenca: 'ServiceConfirmacaoPresenca',
  ServiceEspecialidade: 'ServiceEspecialidade',
  ServiceEvento: 'ServiceEvento',
  ServiceGeneroMusical: 'ServiceGeneroMusical',
  ServiceMidia: 'ServiceMidia',
  ServicePerfil: 'ServicePerfil',
  ServiceServico: 'ServiceServico',
  ServiceUsuario: 'ServiceUsuario',
};

export default TYPES;